# -*- coding: utf-8 -*-
"""MusicPlayerProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjeJD-9mi8lneyUofTH7iK9xxn5q4tr6
"""



class Song:
    def __init__(self, name, artist, album, year):
        self.name = name
        self.artist = artist
        self.album = album
        self.year = year


    def __str__(self):
        return f"Song({self.name}, {self.artist}, {self.album}, {self.year})"

    def __repr__(self):
        return f"Song({self.name}, {self.artist}, {self.album}, {self.year})"

class Playlist:
    def __init__(self):
        self.songs = []

    def load_songs(self, filename):
        try:
            with open(filename, mode="r") as f:
                data = f.read().splitlines()

                for line in data:
                    artist, album, year, name = line.split("\t")
                    song = Song(name, artist, album, year)
                    self.songs.append(song)
        except:
            raise FileNotFoundError(f"{filename} is not found.")

p = Placylist()

p.load_songs("albums.txt")

import time
import random

class Player:
    def __init__(self, file_name):
        self.playlist = Playlist()
        self.playlist.load_songs(file_name)

        self.is_on = False
        self.current_song_index = 0


    def play(self):
        self.is_on = True

        for _ in range(3):
            song = self.playlist.songs[self.current_song_index]

            print(f"Playing song #{self.current_song_index} {song.name}")
            time.sleep(2)

    def show_now_playing(self):
        song = self.playlist.songs[self.current_song_index]
        print(f"#{self.current_song_index}", song)

    def next_song(self):
        if self.is_on:
            if self.current_song_index == len(self.playlist.songs)-1:
                self.current_song_index = 0
            else:
                self.current_song_index += 1

    def prev_song(self):
        if self.is_on:
            if self.current_song_index != 0:
                self.current_song_index -= 1
            else:
                self.current_song_index = len(self.playlist.songs)-1


    def shuffle(self):
        if self.is_on:
            random.shuffle(self.playlist.songs)

    def stop(self):
        if self.is_on:
            self.is_on = False

player = Player('albums.txt')

player.show_now_playing()

player.shuffle()

player.next_song()

player.prev_song()

